### ISSUE TITLE
Budget calculation does not round correctly

### ISSUE THREAD

**Issue by krombel** [brarcher/budget-watch#112]
When having transactions with a sum of e.g. 9.99 it shows as 9 in the budget overview but i would prefer 10 in that case
An alternative would be to show the cents as well (maybe configurable)

**Comment by brarcher** [comment]
Hm. Currently the value which is displayed is the floor() instead of the ceiling(). The decision was arbitrary, as I really only wanted to simplify the display instead of showing cents. If you think that it would be more correct to show the rounded value (as being more conservative in one's spending is the point of the app), that should be easy enough to do. Would that suffice?

**Comment by krombel** [comment]
What do you think of making it configurable to show cents or not?

And would it be possible to have "round" easily? So 9.49- => 9 whereas 9.50+ => 10
If not I think I would prefer ceiling 8)

**Comment by brarcher** [comment]
I think that if someone where interested in adding in a configuration for displaying cents, I would accept the change. I probably will not work on adding that, however.

As for rounding, that is a straight forward change, and probably is the correct way to handle the values. I'll work on rounding the values which are displayed.

**Comment by brarcher** [comment]
This should now be resolved, in that the ceiling value is shown instead of the previous truncated value. If in the next release you find it not working the way you expect, please re-open.
