### ISSUE TITLE
CSV export, no recognizable date

### ISSUE THREAD

**Issue by fazlerabbi37** [brarcher/budget-watch#144]
Hi there. I am using Budget Watch app for a week now. Today I exported a csv form that app. When I opened the csv with LibraOffice Calc in the `data` column it showed the value `1517335200000` which is not a human understandable data. I tried changing the format to date and it did not work. I tried with json and zip as well and got same result. How can I get a human readable data?

**Comment by brarcher** [comment]
The time list is the number of milliseconds since [epoch](https://en.wikipedia.org/wiki/Unix_time), which is 1970-01-01 00:00:00 UTC. The timestamp you mention [converts](https://www.epochconverter.com/) to: Tuesday, January 30, 2018 6:00:00 PM.

[This](https://syslog.me/2012/08/28/dates-from-unix-timestamps-in-openoffice-libreoffice/) reference may help in converting that field to a human readable date in OpenOffice or LibreOffice.

**Comment by fazlerabbi37** [comment]
thank you @brarcher for the epoch explanation. I was able to format the epoch time to human readable by asking a [question](https://unix.stackexchange.com/a/421356/199183) on unix stackexchange as I cloud not open the 3rd [link](https://syslog.me/2012/08/28/dates-from-unix-timestamps-in-openoffice-libreoffice/). Thanks again !
