### ISSUE TITLE
option to add income to TOTAL budget

### ISSUE THREAD

**Issue by freilichthirn** [brarcher/budget-watch#76]
This is a feature request to this wonderfully working app:

The option to add revenue without assigning it to a specific budget could be used to add e.g. your income/salary to balance the TOTAL sum.

At the moment revenues have to be assigned to a budget. Assigning certain revenues to specific budgets is useful but one's overall income should be compared to one's TOTAL expenses and therefore it would make sense to add it to a TOTAL budget or none of one's specific budgets (e.g. groceries).

**Comment by brarcher** [comment]
> This is a feature request to this wonderfully working app:

Glad that the app is useful. (:

In thinking through your request, I have a few questions. 

At present all the revenues and expenses are reflected in the Total. Is your concern only that it does not make as much sense to apply a paycheck to a budget item?

One of the features of the application is that from the Budgets screen one can click on a given budget and see all the transactions for it. If one were able to add a transaction which was not associated with a budget, one would not be able to see a filtered list of only those items. Would this be a concern?

To add this feature, I would likely add the ability to create a transaction which could be budget-less, instead of only limiting it to a revenue transaction. This would mean that the Budget dropdown on the Transaction add screen would have one extra item. Maybe that item would be blank, as one cannot add a Budget which is blank. I would then need to filter out that blank budget when displaying the others on the Budget screen to prevent confusion. However, functionally one can do most of this now. One could create a new budget, say "(none)", and assign something to it. It would still be a budget, but would not apply to the other categories, which may be your concern. Would doing something like adding a new budget just for paychecks be a suitable workaround?

For some background, before I created the application I was using some other application which was free but not open source. That application allowed one to track transactions but also kept running totals on bank accounts, etc. The latter part was not interesting to me, as I was only interested in budgets and spending. The revenue part was incase there was a return to a store, etc, so that the budget total would not be skewed.

Your using the application to keep track of your incoming and outgoing money is perfectly acceptable. It was not my original intent, but there is no reason why your use case should not also work. (:

**Comment by freilichthirn** [comment]
> To add this feature, I would likely add the ability to create a transaction which could be budget-less, instead of only limiting it to a revenue transaction. This would mean that the Budget dropdown on the Transaction add screen would have one extra item. Maybe that item would be blank, as one cannot add a Budget which is blank. I would then need to filter out that blank budget when displaying the others on the Budget screen to prevent confusion.

Yes, a budget-less transaction (=the paycheck item) is what I'm proposing, as a paycheck is budget-less income (to be used an all budgets). And it wouldn't do any harm, if it wasn't displayed on the budget screen as long as its value would be set off against the TOTAL spending and budget sums.

> The  revenue part was incase there was a return to a store, etc, so that the budget total would not be skewed.

Yes, absolutely. This it is the right use case - and I would also use it, if I'd sell something. But both are rather exceptional use cases and don't happen very often, I presume.

> At present all the revenues and expenses are reflected in the Total. Is your concern only that it does not make as much sense to apply a paycheck to a budget item?
Yes, this is my concern, as it does not make any sense rather than "not much" to me ;) A paycheck should be applied to the TOTAL-budget.

Adding a "paycheck"-budget is my workaround around at the moment, that I'm not entirely happy with, because it generates a budget that has only revenues and is therefore displayed with a "-yyyy/0" on the overview Budget screen. The problem is: only the possibility to add a negative budget amount to balance the negative transactions of a paycheck would be a workaround for a revenue only budget like this. As the paycheck in the current setting is added as negative spending, the spendings-TOTAL is correct but the budget-TOTAL is compromised by the 0 value. A fast "fix" to "my" problem would be the possibility to set a negative budget to my paycheck-budget, if you get what I mean. :D 

I totally understand your interest and focus in budget/spending and would appreciate it a lot if you'd find a way to integrate the idea of a paycheck feature.

**Comment by Ketrel** [comment]
I came here to post about the same thing, for the same reason, so I'd like to second some sort of option for applying a paycheck to the total without having it tied to a specific budget.

**Comment by brarcher** [comment]
I'm not opposed to having this feature, especially if there is interest. I may not get around to adding  it right away, however. In the meantime, if someone were to contribute the feature I'd be glad to help them along.

**Comment by brarcher** [comment]
@freilichthirn & @Ketrel, I found some time and worked out this feature. Would either of you be interested in beta-testing it and determining if it works the way you would expect? I'm not sure if you downloaded the application from Google Play or F-Droid, but if you got it from Google attached is a copy of the app with the feature signed with the same key.

[app-release.apk.zip](https://github.com/brarcher/budget-watch/files/1223972/app-release.apk.zip)

**Comment by Ketrel** [comment]
I'd be willing to help beta test, but any chance you can sign it with the key the f-droid version has?

**Comment by brarcher** [comment]
Unfortunately, I do not have that key, as that is owned by the F-droid project.

The application ID for Google play is different than that on F-droid, so if you install the app it will appear as a different app. I would still backup first, but it should not affect your app from F-droid.

On August 21, 2017 1:39:55 PM EDT, Ketrel <notifications@github.com> wrote:
>I'd be willing to help beta test, but any chance you can sign it with
>the key the f-droid version has?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/brarcher/budget-watch/issues/76#issuecomment-323806648

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brarcher** [comment]
I've not heard any feedback about the proposed change in about a month. I'll assume that the change is what you are after, and commit the change. If after you see the change in a release you feel otherwise, re-open this issue.
