### ISSUE TITLE
[quickie] input validation fails when editing and saving

### ISSUE THREAD

**Issue by bughunter2** [brarcher/budget-watch#89]
When editing an existing transaction, input validation may fail for the "value" field even if the user didn't change the value.

This seems to be caused by locale settings and/or string formatting.

For example, if the value field was "13.75" then it is changed to "13,75" at the time of form initialization. The program doesn't allow saving such a value because it expects a dot (not a comma) to be the fractional separator (or decimal mark).

So when the user hits Save she gets a "Value invalid" error message.

Versions: This seems to occur at least in versions 0.11 and 0.12. I have not tested older versions.

**Comment by brarcher** [comment]
Thanks for reporting this issue.

I think I see the issue. When initializing the value field in the form String.format() is used:
```
(updateTransaction ? valueEdit : valueView).setText(String.format("%.2f", transaction.value));
```
and internally that is using the default locale. In your locale using a comma separates the whole number and decimal, correct? The input validator for the Save button uses
```
value = Double.parseDouble(valueStr);
```
which expects to use a period regardless of the locale.

Here then is a question. Is it sufficient to always display floating point numbers with a '.' instead of a ',' (thus resolving this issue but not honoring the locale) or to honor ',' as the decimal separator? Fixing the immediate issue would be simpler, but I do not know how bothersome it is that the decimal separator would be a '.' instead of a ','.

**Comment by bughunter2** [comment]
Hi, thanks for looking into this!

Yes, my native locale uses a comma to separate the whole number and the decimal.

To me it wouldn't matter at all if the decimal separator is always a '.' rather than a ','.
However, I can't speak for all users.

Perhaps it's an idea to use a simple string replacement to convert the first (or any) ',' to a '.' before passing it to Double.parseDouble(). That probably covers most (if not all) locales.

**Comment by brarcher** [comment]
For now I'll simply make a change to force a locale which uses a '.' instead of a ','. I've created another defect to better handle this and display the user's locale and correctly parse back the value.

I'll push out a new release with this fix before too long. If in the next release you find the issue not resolved, please re-open this issue.

**Comment by bughunter2** [comment]
Cheers. Happy hacking. =)
